### ISSUE TITLE
Firmware Version

### ISSUE THREAD

**Issue by jseadragon** [eseglem/pywattbox#2]
Hi there,

I am looking to use this integration myself via the HASS plugin you have created. I am running into some issues and I am starting to think the authentication API has changed slightly since this code was written.

### Original Firmware

Originally on the stock firmware I got these types of errors:
```
curl http://wattbox:80/
<html><body><script language="javascript">
window.top.location.href="login.htm"
curl: (18) transfer closed with outstanding read data remaining
```

### Upgraded firmware
I am now running `WB10.B929` ([released in Dec 2022](https://www.control4.com/docs/product/wattbox-300-series/release-notes/english/latest/wattbox-300-series-release-notes-rev-c.pdf)). It looks like the new firmware is using a cookie instead of authenticating every request using `HTTP Basic Authentication`. I have the initial login flow captured, but before I go down the rabbit hole I wanted to check in first.

I'm happy to submit a PR once I get it working, if you like. What version of the Wattbox firmware are you running?

**Comment by eseglem** [comment]
Yeah, I hadn't seen that update yet. I am still on `WB10.9a17`. Happy to accept a PR if you can get something working.

I haven't tested it much yet, but the develop branch has a major overhaul to try and get things working entirely async, as well as with the newer models. So there may be some bugs in there still, but think it should mostly be ok.

**Comment by jseadragon** [comment]
See the PR #10 for my fix to this problem
